---
title: "Bike rentals - modeling with GBM"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)

# create image folder ----
if (!file.exists("images/")) {
    dir.create("images/")
}
# create data folder ----
if (!file.exists("data/")) {
    dir.create("data/")
}

# knitr settings chunk ------
knitr::opts_chunk$set(
    echo = TRUE, # show all code
    tidy = FALSE, # cleaner code printing
    size = "small", # smaller code
    fig.path = "images/") 

#  knitr settings entire doc ------
knitr::opts_knit$set(
    width = 78)

base::options(tibble.print_max = 25,
              tibble.width = 78)
```



```{r packages, message=FALSE, warning=FALSE}
# packages --------------------------------------------------------------
library(tidyverse)
library(rsample) # data splitting
library(randomForest) # basic implementation
library(ranger) # a faster implementation of randomForest
library(caret) # an aggregator package for performing many machine learning models
library(ggthemes)
library(scales)
library(wesanderson)
library(styler)
```

Run previous scripts to import and wrangle data. 

```{r previous-sripts, message=FALSE, warning=FALSE}
# fs::dir_ls("code")
base::source("code/01-import.R")
base::source("code/02-wrangle.R")
# no need to run code/03-visualize.R becuase it does not change the 
# underlying data
```

Now check for the data in our working environment. 

```{r BikeData}
BikeData %>% glimpse()
```



