---
title: "The Bike Rental Boom Is Here: Predicting Bike Rental Behaviour in a Metropolitan City"
output: 
  github_document: 
    toc: yes
    toc_depth: 5
---


```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)

# create image folder ----
if (!file.exists("images/")) {
    dir.create("images/")
}
# create data folder ----
if (!file.exists("data/")) {
    dir.create("data/")
}

# knitr settings chunk ------
knitr::opts_chunk$set(
    echo = TRUE, # show all code
    tidy = FALSE, # cleaner code printing
    size = "small", # smaller code
    fig.path = "images/") 

#  knitr settings entire doc ------
knitr::opts_knit$set(
    width = 78)

base::options(tibble.print_max = 25,
              tibble.width = 78)
```

# Motivation


```{r packages, message=FALSE, warning=FALSE}
# packages --------------------------------------------------------------
library(tidyverse)
library(rsample) # data splitting
library(randomForest) # basic implementation
library(ranger) # a faster implementation of randomForest
library(caret) # an aggregator package for performing many machine learning models
library(ggthemes)
library(scales)
library(wesanderson)
library(styler)
```

# Import

```{r import-bike}
# read data of bike rentals daily ----
bike <- read.csv("day.csv")
```

# Wrangle

```{r weekday-chr}
# WRANGLE ---------------------------------------------------------------

# recode with labels and make factor
bike <- bike %>%
  mutate(
    weekday_chr =
      case_when(
        weekday == 0 ~ "Sunday",
        weekday == 1 ~ "Monday",
        weekday == 2 ~ "Tuesday",
        weekday == 3 ~ "Wednesday",
        weekday == 4 ~ "Thursday",
        weekday == 5 ~ "Friday",
        weekday == 6 ~ "Saturday",
        TRUE ~ "other"
      )
  )
```

## Weekdays

```{r weekday-fct}
bike %>%
  mutate(
    weekday_fct = factor(x = weekday,
             labels = c(0,1,2,3,4,5,6),
             levels = c("Sunday",
                       "Monday",
                       "Tuesday",
                       "Wednesday",
                       "Thursday",
                       "Friday",
                       "Saturday"))) %>%
  dplyr::count(weekday, weekday_fct) %>% 
  tidyr::spread(weekday, n)

# assign 
bike <- bike %>%
  mutate(
    weekday_fct = factor(x = weekday,
             labels = c(0,1,2,3,4,5,6),
             levels = c("Sunday",
                       "Monday",
                       "Tuesday",
                       "Wednesday",
                       "Thursday",
                       "Friday",
                       "Saturday")))
```

## Holidays


```{r holiday_chr}
bike <- bike %>%
  mutate(
    holiday_chr =
      case_when(
        holiday == 0 ~ "Non-Holiday",
        holiday == 1 ~ "Holiday",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(holiday, holiday_chr) %>% 
  tidyr::spread(holiday, n)
```

## Working days

```{r workingday_chr}
bike <- bike %>%
  mutate(
    workingday_chr =
      case_when(
        workingday == 0 ~ "Non-Working Day",
        workingday == 1 ~ "Working Day",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(workingday, workingday_chr) %>% 
  tidyr::spread(workingday, n)
```

## Seasons

```{r season_chr}
bike <- bike %>%
  mutate(
    season_chr =
      case_when(
        season == 1 ~ "Spring",
        season == 2 ~ "Summer",
        season == 3 ~ "Fall",
        season == 4 ~ "Winter",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(season, season_chr) %>% 
  tidyr::spread(season, n)
```

## Weather situation

```{r weathersit_chr}
bike <- bike %>%
  mutate(
    weathersit_chr =
      case_when(
        weathersit == 1 ~ "Good",
        weathersit == 2 ~ "Clouds/Mist",
        weathersit == 3 ~ "Rain/Snow/Storm",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(weathersit, weathersit_chr) %>% 
  tidyr::spread(weathersit, n)
```

## Months

```{r month_chr}
bike <- bike %>%
  mutate(
    month_chr =
      case_when(
        mnth == 1 ~ "January",
        mnth == 2 ~ "February",
        mnth == 3 ~ "March",
        mnth == 4 ~ "April",
        mnth == 5 ~ "May",
        mnth == 6 ~ "June",
        mnth == 7 ~ "July",
        mnth == 8 ~ "August",
        mnth == 9 ~ "September",
        mnth == 10 ~ "October",
        mnth == 11 ~ "November",
        mnth == 12 ~ "December",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(mnth, month_chr) %>% 
  tidyr::spread(mnth, n)
```

## Years

```{r yr_ch}
bike <- bike %>%
  mutate(
    yr_ch =
      case_when(
        yr == 0 ~ "2011",
        yr == 1 ~ "2012",
        TRUE ~ "other"
      )
  )

bike %>% 
  dplyr::count(yr, yr_ch) %>% 
  tidyr::spread(yr, n)
```

## Temperature

```{r temperature}
# normalize temperatures
bike <- bike %>%
  mutate(temp = as.integer(temp * (39 - (-8)) + (-8)))

bike <- bike %>%
  mutate(atemp = atemp * (50 - (16)) + (16))

# ~ windspeed ----
bike <- bike %>%
  mutate(windspeed = as.integer(67 * bike$windspeed))

# ~ humidity ----
bike <- bike %>%
  mutate(hum = as.integer(100 * bike$hum))
```

## Date

```{r date}
# ~ convert to date ----
bike <- bike %>%
  mutate(dteday = as.Date(dteday))
```

***

# Exploratory Data Analysis

Three options

## dplyr (#1)

```{r bike_dplyr_summary, message=FALSE, warning=FALSE}
# create exploratory analysis table for continuous data
bike_dplyr_summary <- bike %>%
  select(temp, atemp, hum, windspeed, casual, registered, cnt) %>%
  summarise_each(list(
    min = ~min,
    q25 = ~quantile(., 0.25),
    median = ~median,
    q75 = ~quantile(., 0.75),
    max = ~max,
    mean = ~mean,
    sd = ~sd
  )) %>%
  gather(stat, val) %>%
  separate(stat, 
           into = c("var", "stat"), 
           sep = "_") %>%
  spread(stat, val) %>%
  select(var, min, q25, median, q75, max, mean, sd)

knitr::kable(bike_dplyr_summary)
```

## skimr (#2)

```{r bike_summary_skim}
# skimr::skim() ----
bike_summary_skim <- bike %>%
  skimr::skim_to_wide() %>%
  dplyr::select(type,
    variable,
    missing,
    complete,
    min,
    max,
    mean,
    sd,
    median = p50,
    hist)
knitr::kable(bike_summary_skim)
```

## mosaic::inspect (#3)

```{r bike_inspect}
# mosaic::inspect -----------------------------------------------------
bike_inspect <- mosaic::inspect(bike)

# categorical
knitr::kable(bike_inspect$categorical)
```

```{r inspect-Date}
# categorical
knitr::kable(bike_inspect$Date)
```


```{r inspect-quantitative}
# categorical
knitr::kable(bike_inspect$quantitative)
```
